[package]
name = "fvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jm_math = {path = "/Users/h1007185/workspace/Rust/jm_math"}
